### ISSUE TITLE
Find the way to correctly support `garaż` area, `garaż` entity with domain and class_device and also with response correct sentence

### ISSUE THREAD

**Issue by witold-gren** [Uriziel01/home-assistant-intents-pl#5]

**Comment by dziadeck47** [comment]
This one is a 'globally' recognised problem. See here for sequence-> intent syntax ('requires context' part)
https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax/
and here - guidance asking to differentiate entity name from area name for testing purposes
https://developers.home-assistant.io/docs/voice/intent-recognition/test-syntax/

**Comment by witold-gren** [comment]
Hey @dziadeck47, thanks of info (we know about it) but it will not work in our case because have the sam name for `{area}` and `{name}`. In documentation you see:
```
If you have an entity named "kitchen light", then you will be able to say "set kitchen light brightness to maximum". Similarly, "set kitchen brightness to maximum" will work if you have an area named "kitchen".
```
And testing file:
```
# Example _fixtures.yaml for English
language: "en"
areas:
  - name: "Kitchen"
    id: "kitchen"
entities:
  - name: "Kitchen Switch"
    id: "switch.kitchen"
    area: "kitchen"
```
the name of area and entity is different. 

PS. If you have an idea how to do it maybe you will able prepare some PR?
