### ISSUE TITLE
Add Fence gaate - Ogrodzenie as other gate cover

### ISSUE THREAD

**Issue by majkers** [Uriziel01/home-assistant-intents-pl#8]
I think we have to keep in mind that some of us have more than a one gate ie. Garaż... :) As for me I also have fence gate ie. Ogrodzenie. So I had to modify HassTurnOn intent like this:

```
language: "pl"
intents:
  HassTurnOn:
    data:
      - sentences:
          - "<open> ogrodzenie"
          - "<open> bramę ogrodzeniową"
          - "Bramę ogrodzeniową <open>"
        slots:
          domain: cover
          device_class: gate
        response: cover_fence 
        
      - sentences:
          - "<open> [<all>] bramy"
        slots:
          domain: cover
        response: cover_gates   
```

With a new response like this:

```
language: "pl"
responses:
  intents:
    HassTurnOn:
      cover_fence: "Otwarto ogrodzenie"  
      cover_gates: "Otwarto bramy"
```  

I also added some intent to open all gates at one time...

Do you think that it is a good idea to add this ?
